# Permalinks
permalink:           pretty

# Setup
title:               Hanthana Artificial Intelligence Laborotory Blog
tagline:             ""
paginate:		5
baseurl:             /blog

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              HAIL
  url:               ""
  email:             ""

# Custom vars
version:             2.0.0
github:
  repo:              ""

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist


# pages_list:
#   Feed: '/atom.xml'